USE intern_kanban;

CREATE TABLE IF NOT EXISTS `user` (
  `id`            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username`      VARCHAR(50)  NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `nickname`      VARCHAR(50)  NULL,
  `created_at`    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `task` (
  `id`			BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title`		VARCHAR(100) NOT NULL,
  `description`	TEXT NULL,
  `priority` 	ENUM('LOW', 'MEDIUM', 'HIGH') NOT NULL DEFAULT 'MEDIUM',
  `status`		ENUM('TODO', 'DOING', 'DONE') NOT NULL DEFAULT 'TODO',
  `assignee_id` BIGINT UNSIGNED NULL,
  `due_time`	DATETIME NULL,
  `created_at`	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `task_tag` (
  `id`			BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_id`		BIGINT UNSIGNED NOT NULL,
  `tag` 		VARCHAR(100)	NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `task_log` (
  `id`			BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_id`		BIGINT UNSIGNED NOT NULL,
  `from_status`	ENUM('TODO', 'DOING', 'DONE') NULL,
  `to_status`	ENUM('TODO', 'DOING', 'DONE') NULL,
  `operator_id` BIGINT UNSIGNED NULL,
  `created_at`	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;